CREATE MEMORY TABLE "PUBLIC"."PRICE"(
    "ID" INTEGER NOT NULL,
    "BRAND_ID" INTEGER NOT NULL,
    "CURRENCY" VARCHAR(255) NOT NULL,
    "END_DATE" TIMESTAMP NOT NULL,
    "LAST_UPDATE" TIMESTAMP NOT NULL,
    "LAST_UPDATE_BY" VARCHAR(255) NOT NULL,
    "PRICE" DECIMAL(19, 2) NOT NULL,
    "PRICE_LIST" INTEGER NOT NULL,
    "PRIORITY" INTEGER NOT NULL,
    "PRODUCT_ID" BIGINT NOT NULL,
    "START_DATE" TIMESTAMP NOT NULL
)